---
name: GitHub Variables Actions

on:
  # push:
  pull_request:
    # types:
    #   - closed
    #   - reopened
    #   - assigned
  schedule:
    - cron: "0/30 9-17 * * MON-FRI"



jobs: 
  js-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Simple Variables
        run: |
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REF

      # - name: GitHub Token
      #   run: echo "${{ github.token }}"

      # - name: Clone Github my $GITHUB_REPOSITORY
      #   run: |
      #     git clone git@github:$GITHUB_REPOSITORY
      #     git checkout $GITHUB_SHA

